clc
clear
[y,fs]=audioread('../sound/plastic_love2.mp3');%读取音乐信号
y1=y(:,1);%取单列                            
N=length(y1);%求信号长度
Y=fft(y1,N);%傅里叶变换
t=(0:(N-1))/fs;%时间
f=0:fs/N:fs*(N-1)/N;%频率
w=2*f/fs;%归一化
%IIR低通滤波器
wp=0.1;ws=0.2;Rp=1;Rs=15;
[n1,Wn1]=buttord(wp,ws,Rp,Rs,'s');%求低通滤波器的阶数和截止频率
[b1,a1]=butter(n1,Wn1,'s');%求s域的频率响应的参数
[b2,a2]=bilinear(b1,a1,1);%利用双线性变换实现频率响应s域到z域的变换
z1=filter(b2,a2,y1);%滤波后信号
m1=fft(z1);
figure(1);
subplot(2,1,1);
plot(w,abs(Y));
xlabel('w');
ylabel('幅度');
title('原信号频谱');
subplot(2,1,2);
plot(w,abs(m1));
xlabel('w');
ylabel('幅度');
title('低通滤波信号频谱');
%高通滤波器
wp=0.1;ws=0.2;rp=1;rs=15;
[n,Wn]=buttord(wp,ws,rp,rs,'s');%设计模拟滤波器
[z,p,k]=buttap(n);%创建巴特沃斯低通滤波器原型
[b,a]=zp2tf(z,p,k);%由零极点转换为传递函数
[b11,a11]=lp2hp(b,a,Wn);%模拟低通变高通
[b22,a22]=bilinear(b11,a11,0.5);%利用双线性变换实现频率响应S域到Z域的变换
z2=filter(b22,a22,y1);%滤波后信号
m2=fft(z2);
figure(2);
subplot(2,1,1);
plot(w,abs(Y));
xlabel('w');
ylabel('幅度');
title('原信号频谱');
subplot(2,1,2);
plot(w,abs(m2));
xlabel('w');
ylabel('幅度');
title('高通滤波信号频谱');
%幅度谱相位谱交叉
[x,fs0]=audioread('C:\Users\chuxun\Desktop\信息处理课设\音\王菲.wav');
x0=x(:,1); 
x1=x0(1:200000);%信号2截取长度200000
y2=y1(1:200000);%信号1截取长度200000
N=length(x1);
X=fft(x1,N);
Y=fft(y2,N);
t0=(0:(N-1))/fs0;
f0=0:fs0/N:fs0*(N-1)/N;
w0=2*f0/fs0;%数字角频率
%画两信号的幅度谱和相位谱
figure(3);                                 
subplot(2,2,1);
plot(w0,abs(Y));
xlabel('w');
ylabel('幅度');
title('信号1的幅度谱');
subplot(2,2,2);
plot(w0,abs(X));
xlabel('w');
ylabel('幅度');
title('信号2的幅度谱');
subplot(2,2,3);
plot(w0,angle(Y));   
xlabel('w');
ylabel('相位');
title('信号1的相位谱');
subplot(2,2,4);
plot(w0,angle(X));
xlabel('w');
ylabel('相位');
title('信号2的相位谱');
F1=abs(Y).*exp(1i*angle(X));%音乐信号1的幅度谱和音乐信号2的相位谱交叉
F2=abs(X).*exp(1i*angle(Y));%音乐信号2的幅度谱和音乐信号1的相位谱交叉%对交叉得到的频域信号做傅里叶逆变换
y3=real(ifft(F1,N));
y4=real(ifft(F2,N));%对交叉得到的频域信号做傅里叶逆变换
%绘制交叉得到的信号的波形和频谱
figure(4)
subplot(2,2,1);
plot(t0,y3);
xlabel('时间');
ylabel('幅度');
title('1幅度谱和2相位谱交叉信号时域波形');
subplot(2,2,2);
plot(w0,abs(F1));
xlabel('w');
ylabel('幅度');
title('1幅度谱和2相位谱交叉信号频谱');
subplot(2,2,3);
plot(t0,y4);
xlabel('时间');
ylabel('幅度')
title('2幅度谱和1相位谱交叉信号时域波形');
subplot(2,2,4);
plot(w0,abs(F2));
xlabel('w');
ylabel('幅度');
title('2幅度谱和1相位谱交叉信号频谱');
%播放
sound(y1,fs);%原音乐
pause(5);
sound(z1,fs);%低通滤波声音
pause(5);
sound(z2,fs);%高通滤波声音
pause(5);
sound(y3,fs);%幅度谱1与相位谱2交叉
pause(5);
sound(y4,fs);%相位谱1与幅度谱2交叉