clc;clear;
[org_sound,fs_music]=audioread('../sound/plastic_love2.mp3');
len=length(org_sound);
t=0:1/fs_music:(len-1)/fs_music;
%波形绘制
subplot(2,1,1);plot(t,org_sound(:,1));xlabel('t/s');ylabel('幅度');
title('左声道时域波形');axis([0,(len-1)/fs_music,-1,1]);%左声道
subplot(2,1,2);plot(t,org_sound(:,2));xlabel('t/s');ylabel('幅度');
title('右声道时域波形');axis([0,(len-1)/fs_music,-1,1]);%右声道
%频谱绘制
org_fft1=fft(org_sound(:,1)',1024);org_fft2=fft(org_sound(:,2)',1024);
figure(2);
subplot(2,1,1);mstem(org_fft1);title('左声道信号频谱');
subplot(2,1,2);mstem(org_fft2);title('右声道信号频谱');
%不同抽样率下音调变化
Org=audioplayer(org_sound,fs_music);play(Org);pause(3);%采样率为正常时
Org_h=audioplayer(org_sound,fs_music/2);play(Org_h);pause(3);%采样率为原本0.5倍时
Org_d=audioplayer(org_sound,fs_music*2);play(Org_d);pause(3);%采样率为原本2倍时