clc;clear;
[org_sound,fs_music]=audioread('../sound/plastic_love2.mp3');
fc_H=4400000;fc_L=880000;wc_H=pi*2*fc_H;wc_L=pi*2*fc_L;
%载波频率最高取4.4MHz，最低取880KHz
len=length(org_sound);t=0:1/fs_music:(len-1)/fs_music;
fp=0:fs_music/len:fs_music*(len-1)/len;w=2*fp/fs_music;%归一化
org_fft=fft(org_sound(:,1));
carry_H=cos(wc_H*t);carry_L=cos(wc_L*t);
rf_H=(org_sound(:,1)).*carry_H';rfft_H=fft(rf_H);
rf_L=(org_sound(:,1)).*carry_L';rfft_L=fft(rf_L);
%绘图
subplot(3,2,1);plot(t,org_sound(:,1));xlabel('t/s');ylabel('幅度');
title('左声道调制信号时域波形');
subplot(3,2,2);plot(w,abs(org_fft));xlabel('w/\pi');ylabel('幅度');
title('左声道调制信号频谱');
subplot(3,2,3);plot(t,rf_H);xlabel('t/s');ylabel('幅度');
title('左声道AM高频时域波形');
subplot(3,2,4);plot(w,abs(rfft_H));xlabel('w/\pi');ylabel('幅度');
title('左声道AM高频调制频谱');
subplot(3,2,5);plot(t,rf_L);xlabel('t/s');ylabel('幅度');
title('左声道AM低频时域波形');
subplot(3,2,6);plot(w,abs(rfft_L));xlabel('w/\pi');ylabel('幅度');
title('左声道AM低频调制频谱');
%播放调制信号
Org=audioplayer(org_sound,fs_music);play(Org);pause(3);
RF_H=audioplayer(rf_H,fs_music);play(RF_H);pause(3);
RF_L=audioplayer(rf_L,fs_music);play(RF_L);pause(3);