clc;clear;
[org_sound,fs_music]=audioread('../sound/plastic_love2.mp3');
len=length(org_sound);t=0:1/fs_music:(len-1)/fs_music;
fp=0:fs_music/len:fs_music*(len-1)/len;wpic=2*fp/fs_music;%归一化
%加三余弦混合噪声
noise=0.05*(cos(2*pi*3000*t)+cos(2*pi*5000*t)+cos(2*pi*8000*t));
nfft=fft(noise);subplot(3,1,1);plot(wpic,abs(nfft));xlabel('w/\pi');ylabel('幅度');
title('噪声频谱');
noise_sound=org_sound(:,1)+noise';ns_fft=fft(noise_sound);
subplot(3,1,2);plot(t,noise_sound);xlabel('t/s');ylabel('幅度');
title('加噪后音乐信号波形');
subplot(3,1,3);plot(wpic,abs(ns_fft));xlabel('w/\pi');ylabel('幅度');
title('加噪后音乐信号频谱');
%加随机白噪声
noise_w=0.5*rand(len,1);nwfft=fft(noise_w);nwfft(1,1)=0;figure(2);
subplot(3,1,1);plot(wpic,abs(nwfft));xlabel('w/\pi');ylabel('幅度');
title('随机白噪声频谱');
noise_wsound=org_sound(:,1)+noise_w;nws_fft=fft(noise_wsound);nws_fft(1,1)=0;
subplot(3,1,2);plot(t,noise_wsound);xlabel('t/s');ylabel('幅度');
title('加随机白噪声后音乐信号波形');
subplot(3,1,3);plot(wpic,abs(nws_fft));xlabel('w/\pi');ylabel('幅度');
title('加随机白噪声后音乐信号频谱');
%设计巴特沃斯低通滤波器去噪
wp=0.1;ws=0.13;Rp=0.1;Rs=30;%3000/22050=0.136
[N,wn]=buttord(wp,ws,Rp,Rs);%求低通滤波器的阶数和截止频率
[b,a]=butter(N,wn);%求频率响应的参数
fNp=filter(b,a,noise_sound);fNp_fft=fft(fNp);%求滤三余弦混合噪声后的信号
fNwp=filter(b,a,noise_wsound);fNwp_fft=fft(fNwp);%求滤随机白噪声后的信号
figure(3);subplot(2,2,1);plot(t,fNp);xlabel('t/s');ylabel('幅度');
title('滤三余弦混合噪音后信号波形');subplot(2,2,2);plot(wpic,abs(fNp_fft));
xlabel('w/\pi');ylabel('幅度');title('滤三余弦混合噪音后信号频谱');
subplot(2,2,3);plot(t,fNwp);xlabel('t/s');ylabel('幅度');fNwp_fft(1,1)=0;
title('滤随机白噪音后信号波形');subplot(2,2,4);plot(wpic,abs(fNwp_fft));
xlabel('w/\pi');ylabel('幅度');title('滤随机白噪音后信号频谱');
Org=audioplayer(org_sound,fs_music);play(Org);pause(3);
Nosp=audioplayer(noise_sound,fs_music);play(Nosp);pause(3);%三余弦
Noswp=audioplayer(noise_wsound,fs_music);play(Noswp);pause(3);%随机白噪声
fNosp=audioplayer(fNp,fs_music);play(fNosp);pause(3);%滤三余弦后
fNoswp=audioplayer(fNwp,fs_music);play(fNoswp);pause(3);%滤白噪声后