clc;clear;
[org_sound,fs_music]=audioread('../sound/plastic_love2.mp3');
len=length(org_sound);t=0:1/fs_music:(len-1)/fs_music;
fp=0:fs_music/len:fs_music*(len-1)/len;wpic=2*fp/fs_music;%归一化
%设计低通滤波器
wp=0.1;ws=0.2;Rp=0.1;Rs=30;
[N1,wn1]=buttord(wp,ws,Rp,Rs);%求低通滤波器的阶数和截止频率
[b1,a1]=butter(N1,wn1);%求频率响应的参数
fLsound=filter(b1,a1,org_sound(:,1));fLs_fft=fft(fLsound);
org_fft=fft(org_sound(:,1));subplot(2,1,1);plot(wpic,abs(org_fft));
xlabel('w/\pi');ylabel('幅度');title('原始信号频谱');
subplot(2,1,2);plot(wpic,abs(fLs_fft));xlabel('w/\pi');ylabel('幅度');
title('经低通滤波器后信号频谱');
%设计高通滤波器
wp=0.3;ws=0.2;Rp=0.1;Rs=30;
[N2,wn2]=buttord(wp,ws,Rp,Rs);%求高通滤波器的阶数和截止频率
[b2,a2]=butter(N2,wn2,'high');%求频率响应的参数
fHsound=filter(b2,a2,org_sound(:,1));fHs_fft=fft(fHsound);
figure(2);subplot(2,1,1);plot(wpic,abs(org_fft));
xlabel('w/\pi');ylabel('幅度');title('原始信号频谱');
subplot(2,1,2);plot(wpic,abs(fHs_fft));xlabel('w/\pi');ylabel('幅度');
title('经高通滤波器后信号频谱');
%相频信息影响
[Tian_sound,fs_tian]=audioread('../sound/小田正和.mp3');
cut1=org_sound(1:400000);cut2=Tian_sound(1:400000);len_N=length(cut1);
Zhu_fft=fft(org_sound(:,1),len_N);Tian_fft=fft(Tian_sound(:,1),len_N);
t1=0:1/fs_music:(len_N-1)/fs_music;
fp1=0:fs_music/len_N:fs_music*(len_N-1)/len_N;wpic1=2*fp1/fs_music;%归一化
%画两信号幅度谱和相位谱
figure(3);subplot(2,2,1);plot(wpic1,abs(Zhu_fft));
xlabel('w/\pi');ylabel('幅度');title('信号1幅度谱');
subplot(2,2,2);plot(wpic1,angle(Zhu_fft));
xlabel('w/\pi');ylabel('相位');title('信号1相位谱');
subplot(2,2,3);plot(wpic1,abs(Tian_fft));
xlabel('w/\pi');ylabel('幅度');title('信号2幅度谱');
subplot(2,2,4);plot(wpic1,angle(Tian_fft));
xlabel('w/\pi');ylabel('相位');title('信号2相位谱');
cros1=abs(Zhu_fft).*exp(1i*angle(Tian_fft));%信号1的幅度谱和信号2的相位谱交叉
cros2=abs(Tian_fft).*exp(1i*angle(Zhu_fft));%信号2的幅度谱和信号1的相位谱交叉
CoZhu=real(ifft(cros1,len_N));CoTian=real(ifft(cros2,len_N));%逆变换
%画两交叉信号的波形和频谱
figure(4);subplot(2,2,1);plot(t1,CoZhu);xlabel('t/s');ylabel('幅度');
title('信号1幅度谱交叉信号2相位谱信号波形');
subplot(2,2,2);plot(wpic1,abs(cros1));xlabel('w/\pi');ylabel('幅度');
title('信号1幅度谱交叉信号2相位谱信号频谱');
subplot(2,2,3);plot(t1,CoTian);xlabel('t/s');ylabel('幅度');
title('信号2幅度谱交叉信号1相位谱信号波形');
subplot(2,2,4);plot(wpic1,abs(cros2));xlabel('w/\pi');ylabel('幅度');
title('信号2幅度谱交叉信号1相位谱信号频谱');
%播放
Org=audioplayer(org_sound,fs_music);play(Org);pause(3);
FLS=audioplayer(fLsound,fs_music);play(FLS);pause(3);%经过低通
FHS=audioplayer(fHsound,fs_music);play(FHS);pause(3);%经过高通
CROs1=audioplayer(CoZhu,fs_music);play(CROs1);pause(3);%经过
CROs2=audioplayer(CoTian,fs_music);play(CROs2);pause(3);%经过